import { allBandKeys } from '../road/Biomes.js';

export const ASSET_MANIFEST = {
  // Biome parallax bands — derived from the biome table itself so the
  // manifest can never drift out of sync with what the backdrop asks for.
  // Generated by scripts/buildBiomeBands.js (placeholder art).
  biomes: allBandKeys().map(k => ({ key: k, path: `assets/scenery/biomes/${k}.png` })),

  // North Bend hand-made ground plate — a perspective terrain triangle that
  // sits BETWEEN the terrain grass and the road surface (see the
  // terrain/road split in GameScene).  Source art lives untouched in
  // assets/scenery/north_bend/final/.
  // Seamless top-down ground tile.  NOT a perspective plate — the renderer
  // applies perspective per road segment, so this must stay flat/overhead or
  // the projection gets applied twice.
  // One tile per biome (Ch.9 spec).  All eight were authored back in July but
  // only the PNW one was ever registered — the other seven sat unshipped in
  // the gitignored Archive/, so every region east of the Cascades rendered a
  // wet Pacific-Northwest roadside.  Keys must stay `ground_<name>` to match
  // GROUND_TILES in src/road/GroundPlane.js.
  groundTextures: [
    { key: 'ground_pnw_roadside',
      path: 'assets/scenery/ground_textures/final/pnw_roadside_ground_1024.png' },
    { key: 'ground_seattle',
      path: 'assets/scenery/ground_textures/final/seattle_ground_1024.png' },
    { key: 'ground_north_bend',
      path: 'assets/scenery/ground_textures/final/north_bend_ground_1024.png' },
    { key: 'ground_pass_alpine',
      path: 'assets/scenery/ground_textures/final/pass_alpine_ground_1024.png' },
    { key: 'ground_easton',
      path: 'assets/scenery/ground_textures/final/easton_ground_1024.png' },
    { key: 'ground_kittitas',
      path: 'assets/scenery/ground_textures/final/kittitas_ground_1024.png' },
    { key: 'ground_vantage_basalt',
      path: 'assets/scenery/ground_textures/final/vantage_basalt_ground_1024.png' },
    { key: 'ground_columbia',
      path: 'assets/scenery/ground_textures/final/columbia_ground_1024.png' },
    { key: 'ground_palouse',
      path: 'assets/scenery/ground_textures/final/palouse_ground_1024.png' },

    // ── Snoqualmie roadside snow accumulation (2026-08-12) ──────────────
    // Four stages of the SAME ground, so snow builds up beside the road on the
    // climb instead of switching from bare to white at one mile. Stage 1 is
    // `ground_pass_alpine` above — these are stages 2-4. All 1024×1024 and
    // authored at the same world scale, which is what lets two of them be
    // cross-faded on identical UVs without the detail doubling.
    // Progression lives in GroundPlane.snowGroundAt(); this is only the load.
    { key: 'ground_snoq_light',
      path: 'assets/scenery/ground_textures/final/snoqualmie_ground_light_1024.png' },
    { key: 'ground_snoq_partial',
      path: 'assets/scenery/ground_textures/final/snoqualmie_ground_partial_1024.png' },
    { key: 'ground_snoq_full',
      path: 'assets/scenery/ground_textures/final/snoqualmie_ground_1024.png' },
  ],

  // ── Tunnel facade plates (Ch.2 TUNNEL_FACE_ART_SPEC.md) ─────────────────
  // 1600×900 RGBA. The road openings are TRANSPARENT — the procedural tunnel
  // shell, road, lane lines and vehicles show through them. These are drawn as
  // projected UV-mapped meshes (src/road/TunnelFaceMesh.js), never as flat
  // Images: a sprite with one x/y/scale reads as a cardboard cutout the moment
  // the road curves or the player moves laterally.
  // NOTE: opening geometry per plate is declared in TunnelFaceMesh.PLATES —
  // keep the two in step if the art is ever re-exported.
  // Unconditional since 2026-08-13 — the facades shipped on-by-default and the
  // dev-host gate (constants.tunnelArtEnabled + ?tunnelart overrides) was
  // retired, per this block's own instruction to drop the ternary that day.
  tunnelFaces: [
    { key: 'tunnel_face_mt_baker',
      path: 'assets/scenery/tunnels/tunnel_mt_baker_full.png' },
    { key: 'tunnel_face_mercer_lid',
      path: 'assets/scenery/tunnels/tunnel_mercer_full.png' },
    { key: 'tunnel_face_wildlife',
      path: 'assets/scenery/tunnels/tunnel_wildlife_crossing_face.png' },
    // Wing walls and foreground berms are no longer loaded: Mt Baker and Mercer
    // now ship as full composites that already contain them (2026-08-12). Two
    // of those plates were also deleted from disk, so keeping the keys would
    // have 404'd on every boot.
  ],

  // Seamless overhead asphalt tiles, one per road material along the route.
  // Same rules as the ground tile: flat/overhead art only (RoadPlane applies
  // the perspective per road segment, so a pre-perspective source would get
  // projected twice), and POWER-OF-TWO or GL_REPEAT is unavailable and the
  // layer disables itself.
  //
  // These are DERIVED from the 1254px source art in assets/scenery/roads/ by
  // scripts/buildRoadTextures.js, which resamples to 1024 and re-encodes to
  // WebP (11 MB of PNG → 1.05 MB).  Re-run it after replacing the art, and
  // paste the printed mean values into ROAD_MATERIALS in RoadMaterial.js.
  roadTextures: [
    { key: 'road_asphalt_westside',
      path: 'assets/scenery/roads/final/road_asphalt_westside_wet_1024.webp' },
    { key: 'road_asphalt_mountain',
      path: 'assets/scenery/roads/final/road_asphalt_mountain_1024.webp' },
    { key: 'road_asphalt_eastern',
      path: 'assets/scenery/roads/final/road_asphalt_eastern_dry_1024.webp' },
  ],

  northBend: [
    // Base plate: ground + side hills + valley notch, transparent sky.
    // 1672x941 is exactly 16:9, so it scales to the 800x450 viewport with no
    // distortion.  Replaces both the wedge bands and the old ground triangle.
    { key: 'nb_base_plate',
      path: 'assets/scenery/north_bend/final/north_bend_transition_east.png' },
    // Six hero peaks, miles 28-54.  landmark_mount_si is real art cropped
    // from the Mount Si plate; the other five are crude placeholder
    // silhouettes so the approach curve can be tuned before art exists.
    // Real peaks drop in at these same keys.
    { key: 'landmark_mount_si',
      path: 'assets/scenery/north_bend/final/landmark_mount_si.png' },
    { key: 'landmark_mount_washington',
      path: 'assets/scenery/north_bend/final/landmark_mount_washington.png' },
    { key: 'landmark_mcclellan_butte',
      path: 'assets/scenery/i90_cascades_landmarks/final/mcclellan_butte_eastbound_v2.png' },
    { key: 'landmark_granite_mtn',
      path: 'assets/scenery/i90_cascades_landmarks/final/granite_bandera_eastbound_v2.png' },
    // One plate covers BOTH Snoqualmie Mountain and Guye Peak, so the two
    // table entries collapse into this single landmark.
    { key: 'landmark_snoqualmie_mtn',
      path: 'assets/scenery/i90_cascades_landmarks/final/snoqualmie_guye_eastbound_v3.png' },
  ],

  cars: [
    // ── YAW-BILLBOARD SPIKE (placeholder art) ───────────────────────────
    // Six rear-view frames of one sedan at increasing yaw, generated by
    // scripts/buildCarYawFrames.js.  Deliberately crude flat-shaded boxes:
    // the spike is proving the angle math, not the look.  Real photoreal
    // frames drop in at these same keys provided they keep the generator's
    // framing convention (see spike/frames.json).  Toggle in-game with Y.
    { key: 'spike_sedan_back_y00', path: 'assets/cars/spike/spike_sedan_back_y00.png' },
    { key: 'spike_sedan_back_y08', path: 'assets/cars/spike/spike_sedan_back_y08.png' },
    { key: 'spike_sedan_back_y16', path: 'assets/cars/spike/spike_sedan_back_y16.png' },
    { key: 'spike_sedan_back_y24', path: 'assets/cars/spike/spike_sedan_back_y24.png' },
    { key: 'spike_sedan_back_y34', path: 'assets/cars/spike/spike_sedan_back_y34.png' },
    { key: 'spike_sedan_back_y45', path: 'assets/cars/spike/spike_sedan_back_y45.png' },

    { key: 'car_player',      path: 'assets/cars/player.webp' },
    { key: 'car_beater',      path: 'assets/cars/beater.png' },
    // (muscle / lowrider / interceptor / van removed — only Garage.js
    //  referenced them and Garage was vestigial / deleted in cleanup.)
    // (car_sports/car_truck + the flat car_back_*/car_front_*/car_*_truck_blue
    //  color-variant set removed 2026-07-30 — dead since CAR_COLOR_SETS
    //  migrated to the codex_*/npc_* art below; the files never existed in
    //  public/assets/cars/ either, so these were pure 404 noise on every boot.)
    // Police — front/back pair used by all police cop kinds.
    { key: 'car_back_police',  path: 'assets/cars/car_back_police.png' },
    { key: 'car_front_police', path: 'assets/cars/car_front_police.png' },
    // SWAT — front/back pair used by 4★+ heavy units (do 2× damage).
    { key: 'car_back_swat',    path: 'assets/cars/car_back_swat.png' },
    { key: 'car_front_swat',   path: 'assets/cars/car_front_swat.png' },
    // Codex upgraded vehicle art — front/back pairs for premium garage cars.
    { key: 'codex_beater_back',          path: 'assets/cars/codex/codex_beater_back.png' },
    // Rear-three-quarter steering pose for the genre starter (~12-15° off
    // straight, one direction only — the renderer mirrors it for the other).
    // Default path = the DEFAULT_GENRE art; genreArtPath overrides per plate.
    { key: 'codex_beater_back_turn',     path: 'assets/culture/hiphop_phonk/vehicles/starter_back_turn.png' },
    // ── STEERING ANGLE FRAMES (2026-08-27) ───────────────────────────────
    // True 7° / 12° steering poses — the legacy single back_turn above stays
    // only as a fallback for art sets that lack these.
    { key: 'codex_beater_back_turn_007', path: 'assets/culture/hiphop_phonk/vehicles/starter_back_turn_007.png' },
    { key: 'codex_beater_back_turn_012', path: 'assets/culture/hiphop_phonk/vehicles/starter_back_turn_012.png' },
    // ── PIT SPIN FRAMES (2026-08-22) ─────────────────────────────────────
    // The player's car rotating away from the camera at 30/60/90/120/150°.
    // Played as a short sequence when a cop lands a PIT, so the maneuver reads
    // as YOUR car being spun rather than a damage number appearing.
    // Same convention as codex_beater_back_turn: default path is the
    // DEFAULT_GENRE art and genreArtPath swaps in the plate's own genre.
    { key: 'codex_beater_spin_030',      path: 'assets/culture/hiphop_phonk/vehicles/starter_spin_030.png' },
    { key: 'codex_beater_spin_060',      path: 'assets/culture/hiphop_phonk/vehicles/starter_spin_060.png' },
    { key: 'codex_beater_spin_090',      path: 'assets/culture/hiphop_phonk/vehicles/starter_spin_090.png' },
    { key: 'codex_beater_spin_120',      path: 'assets/culture/hiphop_phonk/vehicles/starter_spin_120.png' },
    { key: 'codex_beater_spin_150',      path: 'assets/culture/hiphop_phonk/vehicles/starter_spin_150.png' },
    { key: 'codex_beater_front',         path: 'assets/cars/codex/codex_beater_front.png' },
    { key: 'codex_suv4x4_back',          path: 'assets/cars/codex/codex_suv4x4_back.png' },
    { key: 'codex_suv4x4_front',         path: 'assets/cars/codex/codex_suv4x4_front.png' },
    { key: 'codex_used_truck_back',      path: 'assets/cars/codex/codex_used_truck_back.png' },
    { key: 'codex_used_truck_front',     path: 'assets/cars/codex/codex_used_truck_front.png' },
    { key: 'codex_new_truck_back',       path: 'assets/cars/codex/codex_new_truck_back.png' },
    { key: 'codex_new_truck_front',      path: 'assets/cars/codex/codex_new_truck_front.png' },
    { key: 'codex_ev_truck_back',        path: 'assets/cars/codex/codex_ev_truck_back.png' },
    { key: 'codex_ev_truck_front',       path: 'assets/cars/codex/codex_ev_truck_front.png' },
    { key: 'codex_sports_car_back',      path: 'assets/cars/codex/codex_sports_car_back.png' },
    { key: 'codex_sports_car_front',     path: 'assets/cars/codex/codex_sports_car_front.png' },
    { key: 'codex_bestla_roadster_back', path: 'assets/cars/codex/codex_bestla_roadster_back.png' },
    { key: 'codex_bestla_roadster_front', path: 'assets/cars/codex/codex_bestla_roadster_front.png' },
    { key: 'codex_playdout_s3x_back',  path: 'assets/cars/codex/bestla_playdout_s3x_back.png' },
    { key: 'codex_playdout_s3x_front', path: 'assets/cars/codex/bestla_playdout_s3x_front.png' },
    // ── Beater first-person cockpit (transparent PNG overlay) ─────────
    // Native 1672×941, scaled to fill the 800×450 viewport.  Drawn in
    // GameScene._buildCockpit / _renderCockpit when the active vehicle
    // is `beater`.  Other vehicles continue using the third-person
    // playerSprite until their own cockpit art ships.
    { key: 'beater_cockpit_base',         path: 'assets/cars/codex/cockpit/beater_cockpit_no_wheel.png' },
    { key: 'beater_steering_wheel',       path: 'assets/cars/codex/cockpit/beater_steering_wheel.png' },
    { key: 'beater_speedometer_needle',   path: 'assets/cars/codex/cockpit/beater_speedometer_needle.png' },
    { key: 'beater_fuel_needle',          path: 'assets/cars/codex/cockpit/beater_fuel_needle.png' },
    { key: 'beater_low_fuel_light',       path: 'assets/cars/codex/cockpit/beater_low_fuel_light.png' },
    { key: 'beater_wiper_arm',            path: 'assets/cars/codex/cockpit/beater_wiper_arm.png' },
    // Traffic aliases for the Codex garage cars.  GameScene resolves NPC
    // traffic with car_back_<set> / car_front_<set> keys.
    { key: 'car_back_codex_beater',          path: 'assets/cars/codex/codex_beater_back.png' },
    { key: 'car_front_codex_beater',         path: 'assets/cars/codex/codex_beater_front.png' },
    { key: 'car_back_codex_suv4x4',          path: 'assets/cars/codex/codex_suv4x4_back.png' },
    { key: 'car_front_codex_suv4x4',         path: 'assets/cars/codex/codex_suv4x4_front.png' },
    { key: 'car_back_codex_used_truck',      path: 'assets/cars/codex/codex_used_truck_back.png' },
    { key: 'car_front_codex_used_truck',     path: 'assets/cars/codex/codex_used_truck_front.png' },
    { key: 'car_back_codex_new_truck',       path: 'assets/cars/codex/codex_new_truck_back.png' },
    { key: 'car_front_codex_new_truck',      path: 'assets/cars/codex/codex_new_truck_front.png' },
    { key: 'car_back_codex_ev_truck',        path: 'assets/cars/codex/codex_ev_truck_back.png' },
    { key: 'car_front_codex_ev_truck',       path: 'assets/cars/codex/codex_ev_truck_front.png' },
    { key: 'car_back_codex_sports_car',      path: 'assets/cars/codex/codex_sports_car_back.png' },
    { key: 'car_front_codex_sports_car',     path: 'assets/cars/codex/codex_sports_car_front.png' },
    { key: 'car_back_codex_bestla_roadster', path: 'assets/cars/codex/codex_bestla_roadster_back.png' },
    { key: 'car_front_codex_bestla_roadster', path: 'assets/cars/codex/codex_bestla_roadster_front.png' },
    // Extra civilian NPC traffic variants.
    { key: 'car_back_npc_hatchback',  path: 'assets/cars/codex/car_npc_hatchback_back.png' },
    { key: 'car_front_npc_hatchback', path: 'assets/cars/codex/car_npc_hatchback_front.png' },
    { key: 'car_back_npc_minivan',    path: 'assets/cars/codex/car_npc_minivan_back.png' },
    { key: 'car_front_npc_minivan',   path: 'assets/cars/codex/car_npc_minivan_front.png' },
    { key: 'car_back_npc_wagon',      path: 'assets/cars/codex/car_npc_wagon_back.png' },
    { key: 'car_front_npc_wagon',     path: 'assets/cars/codex/car_npc_wagon_front.png' },
    // Eastern WA freight + farm equipment.  Semis share one back image but
    // use two front variants (red / green) for visual variety.  Tractor
    // is BACK-only — only spawns same-direction (player always overtakes,
    // never head-on).  Work truck is slower than white truck.
    { key: 'car_back_codex_semi',          path: 'assets/cars/codex/codex_semi_back.png' },
    { key: 'car_front_codex_semi_red',     path: 'assets/cars/codex/codex_semi_red_front.png' },
    { key: 'car_front_codex_semi_green',   path: 'assets/cars/codex/codex_semi_green_front.png' },
    // Semi colorSet aliases — the NPC traffic loader picks ONE colorSet
    // per car, so register both red and green semis as their own sets
    // pointing at the shared back image.
    { key: 'car_back_codex_semi_red',      path: 'assets/cars/codex/codex_semi_back.png' },
    { key: 'car_back_codex_semi_green',    path: 'assets/cars/codex/codex_semi_back.png' },
    { key: 'car_back_codex_tractor',       path: 'assets/cars/codex/codex_tractor_back.png' },
    { key: 'car_back_codex_white_truck',   path: 'assets/cars/codex/codex_white_truck_back.png' },
    { key: 'car_front_codex_white_truck',  path: 'assets/cars/codex/codex_white_truck_front.png' },
    { key: 'car_back_codex_work_truck',    path: 'assets/cars/codex/codex_work_truck_back.png' },
    { key: 'car_front_codex_work_truck',   path: 'assets/cars/codex/codex_work_truck_front.png' },
    // Side-view police images for cars parked on the shoulder.  Random
    // roadside cop encounters use these — left-shoulder cops face right
    // (toward the road) and vice versa.
    { key: 'car_left_police',  path: 'assets/cars/car_left_police.png' },
    { key: 'car_right_police', path: 'assets/cars/car_right_police.png' },
  ],
  // Road-trip "vices" — junk-food / fatigue pickups (reskinned from vices).
  // Art lives in public/assets/vices/; procedural placeholders fill in until
  // each PNG is dropped there.
  vices: [
    { key: 'vice_sushi',    path: 'assets/vices/sushi.png?v=reskin-4' },
    { key: 'vice_burrito',  path: 'assets/vices/burrito.png?v=reskin-4' },
    { key: 'vice_energy',   path: 'assets/vices/energy_shot.png?v=reskin-4' },
    { key: 'vice_gummies',  path: 'assets/vices/gummies.png?v=reskin-4' },
    { key: 'vice_hotdog',   path: 'assets/vices/hotdog.png?v=reskin-4' },
    { key: 'vice_combo',    path: 'assets/vices/combo_meal.png?v=reskin-4' },
    { key: 'vice_coldbrew', path: 'assets/vices/cold_brew.png?v=reskin-4' },
    { key: 'vice_coma',     path: 'assets/vices/food_coma.png?v=reskin-4' },
    { key: 'vice_slushie',  path: 'assets/vices/slushie.png?v=reskin-4' },
    { key: 'vice_caffeine', path: 'assets/vices/caffeine_pills.png?v=reskin-4' },
    { key: 'vice_water',     path: 'assets/vices/water.png?v=reskin-4' },
    { key: 'vice_dramamine', path: 'assets/vices/dramamine.png?v=reskin-4' },
  ],
  // Power-ups: Redneck Rage (invincible rampage) + Emergency Espresso (rescue).
  powerups: [
    { key: 'powerup_rage',     path: 'assets/vices/redneck_rage.png?v=reskin-4' },
    { key: 'powerup_espresso', path: 'assets/vices/emergency_espresso.png?v=reskin-4' },
  ],
  // Windshield splats: ten matching Lucky-Charms-shaped vomit sprites.  The
  // source PNGs are capped at 85% opacity so the road remains faintly visible.
  effects: [
    { key: 'vomit_1',  path: 'assets/ui/sickness/vomit_1.png?v=charms-streaked-1' },
    { key: 'vomit_2',  path: 'assets/ui/sickness/vomit_2.png?v=charms-streaked-1' },
    { key: 'vomit_3',  path: 'assets/ui/sickness/vomit_3.png?v=charms-streaked-1' },
    { key: 'vomit_4',  path: 'assets/ui/sickness/vomit_4.png?v=charms-streaked-1' },
    { key: 'vomit_5',  path: 'assets/ui/sickness/vomit_5.png?v=charms-streaked-1' },
    { key: 'vomit_6',  path: 'assets/ui/sickness/vomit_6.png?v=charms-streaked-1' },
    { key: 'vomit_7',  path: 'assets/ui/sickness/vomit_7.png?v=charms-streaked-1' },
    { key: 'vomit_8',  path: 'assets/ui/sickness/vomit_8.png?v=charms-streaked-1' },
    { key: 'vomit_9',  path: 'assets/ui/sickness/vomit_9.png?v=charms-streaked-1' },
    { key: 'vomit_10', path: 'assets/ui/sickness/vomit_10.png?v=charms-streaked-1' },
  ],
  // NPC portraits for the rest-stop encounter cards.  Missing files fall back
  // to the procedural colored-bust placeholder (BootScene._makeNpcPlaceholder),
  // so the game runs before the art exists.  Drop real art into public/assets/npc/.
  npc: [
    { key: 'npc_street_weirdo',  path: 'assets/npc/street_weirdo.png' },
    { key: 'npc_chain_guy',      path: 'assets/npc/chain_guy.png' },
    { key: 'npc_ski_bum',        path: 'assets/npc/ski_bum.png' },
    { key: 'npc_long_haul_mike', path: 'assets/npc/long_haul_mike.png' },
    { key: 'npc_farm_worker',    path: 'assets/npc/farm_worker.png' },
    { key: 'npc_biz_founder',    path: 'assets/npc/biz_founder.png' },
    { key: 'npc_hiker_woman',    path: 'assets/npc/hiker_woman.png' },
    { key: 'npc_park_ranger',    path: 'assets/npc/park_ranger.png' },
    { key: 'npc_diner_waitress', path: 'assets/npc/diner_waitress.png' },
    { key: 'npc_grandma',        path: 'assets/npc/grandma.png' },
    { key: 'npc_tow_driver',     path: 'assets/npc/tow_driver.png' },
    { key: 'npc_swimsuit_girl',  path: 'assets/npc/swimsuit_girl.png' },
  ],
  // Shop-staff portraits — one per business brand, same 1086x1448 spec as the
  // npc: array above.  Each is a close-up of the SAME character already
  // visible in that brand's full-bleed storefront background (see
  // shop_bg_* in the businesses: array).  Keyed to match SHOP_BG /
  // stopBrands in RestStopScene.js so a future render pass can look one up
  // by shop id directly.  NOT YET RENDERED anywhere — registered only.
  npcBusinesses: [
    { key: 'npc_biz_huffs',      path: 'assets/npc/businesses/huffs_attendant.png' },
    { key: 'npc_biz_cargo',      path: 'assets/npc/businesses/cargo_dispatcher.png' },
    { key: 'npc_biz_cowbellas',  path: 'assets/npc/businesses/cowbellas_shopkeeper.png' },
    { key: 'npc_biz_aok',        path: 'assets/npc/businesses/aok_host.png' },
    { key: 'npc_biz_lord',       path: 'assets/npc/businesses/lord_manager.png' },
    { key: 'npc_biz_suck',       path: 'assets/npc/businesses/sams_owner.png' },
    { key: 'npc_biz_gasnsip',    path: 'assets/npc/businesses/gasnsip_clerk.png' },
    { key: 'npc_biz_am_bm',      path: 'assets/npc/businesses/ambm_clerk.png' },
    { key: 'npc_biz_parkride',   path: 'assets/npc/businesses/parkride_courier.png' },
    { key: 'npc_biz_schwasted',  path: 'assets/npc/businesses/les_schwasted_tech.png' },
    { key: 'npc_biz_fap',        path: 'assets/npc/businesses/fap_technician.png' },
  ],
  buildings: [
    { key: 'space_needle', path: 'assets/buildings/codex/space_needle_landmark.png' },
    // Codex real-reference scenery pass — transparent cutout candidates
    // grounded in Seattle / Bellevue / Issaquah reference architecture.
    { key: 'codex_seattle_skyline',         path: 'assets/buildings/codex/seattle_skyline_cluster.png' },
    { key: 'codex_seattle_tower_pair',      path: 'assets/buildings/codex/seattle_tower_pair.png' },
    { key: 'codex_seattle_office_cluster',  path: 'assets/buildings/codex/seattle_office_cluster.png' },
    { key: 'codex_bellevue_skyline',        path: 'assets/buildings/codex/bellevue_skyline_cluster.png' },
    { key: 'codex_bellevue_wavy_residential', path: 'assets/buildings/codex/bellevue_wavy_residential.png' },
    { key: 'codex_bellevue_city_center_dark', path: 'assets/buildings/codex/bellevue_city_center_dark.png' },
    { key: 'codex_bellevue_braced_glass_tower', path: 'assets/buildings/codex/bellevue_braced_glass_tower.png' },
    { key: 'codex_bellevue_residential_cluster', path: 'assets/buildings/codex/bellevue_residential_cluster.png' },
    { key: 'codex_seattle_columbia_center', path: 'assets/buildings/codex/seattle_columbia_center.png' },
    { key: 'codex_seattle_rainier_square',  path: 'assets/buildings/codex/seattle_rainier_square.png' },
    { key: 'codex_seattle_two_union_square', path: 'assets/buildings/codex/seattle_two_union_square.png' },
    { key: 'codex_seattle_1201_third',      path: 'assets/buildings/codex/seattle_1201_third.png' },
    { key: 'codex_seattle_municipal_tower', path: 'assets/buildings/codex/seattle_municipal_tower.png' },
    { key: 'codex_seattle_f5_tower',        path: 'assets/buildings/codex/seattle_f5_tower.png' },
    { key: 'codex_seattle_safeco_plaza',    path: 'assets/buildings/codex/seattle_safeco_plaza.png' },
    { key: 'codex_seattle_city_centre',     path: 'assets/buildings/codex/seattle_city_centre.png' },
    { key: 'codex_seattle_russell_investments', path: 'assets/buildings/codex/seattle_russell_investments.png' },
    { key: 'codex_seattle_lumen_field',     path: 'assets/buildings/codex/seattle_lumen_field.png' },
    { key: 'codex_seattle_tmobile_park',    path: 'assets/buildings/codex/seattle_tmobile_park.png' },
    { key: 'codex_bellevue_roadside_strip', path: 'assets/buildings/codex/bellevue_roadside_strip.png' },
    // Directional variants — angle-matched for the side of the road
    // they spawn on so the façade faces the player as they pass.
    { key: 'codex_pse_bellevue_office_left',         path: 'assets/buildings/codex/bellevue_pse_office_left.png' },
    { key: 'codex_pse_bellevue_office_right',        path: 'assets/buildings/codex/bellevue_pse_office_right.png' },
    { key: 'codex_pse_bellevue_second_office_left',  path: 'assets/buildings/codex/bellevue_pse_second_office_left.png' },
    { key: 'codex_pse_bellevue_second_office_right', path: 'assets/buildings/codex/bellevue_pse_second_office_right.png' },
    { key: 'codex_bellevue_twin_residential_left',   path: 'assets/buildings/codex/bellevue_twin_residential_left.png' },
    { key: 'codex_issaquah_front_supply',   path: 'assets/buildings/codex/issaquah_front_st_supply.png' },
    { key: 'codex_issaquah_highlands',      path: 'assets/buildings/codex/issaquah_highlands_market.png' },
    { key: 'codex_issaquah_cottage',        path: 'assets/buildings/codex/issaquah_craftsman_cottage.png' },
    { key: 'codex_issaquah_roadside_strip_perspective', path: 'assets/buildings/codex/issaquah_roadside_strip_perspective.png' },
    // Compact dry-side town/farm cutouts. Runtime copies are cropped WebP
    // assets; the full generated originals live under Archive/.
    { key: 'codex_cle_elum_general_store',      path: 'assets/buildings/codex/cle_elum_general_store.webp' },
    { key: 'codex_ellensburg_main_street_shops', path: 'assets/buildings/codex/ellensburg_main_street_shops.webp' },
    { key: 'codex_east_wa_weathered_house',     path: 'assets/buildings/codex/east_wa_weathered_house.webp' },
    { key: 'codex_east_wa_barn',                path: 'assets/buildings/codex/east_wa_barn.webp' },
    { key: 'codex_east_wa_abandoned_bungalow',  path: 'assets/buildings/codex/east_wa_abandoned_bungalow.webp' },
    { key: 'codex_east_wa_silos',               path: 'assets/buildings/codex/east_wa_silos.png' },
    { key: 'codex_east_wa_brick_storefront_1',  path: 'assets/buildings/codex/east_wa_brick_storefront_1.webp' },
    { key: 'codex_east_wa_brick_storefront_2',  path: 'assets/buildings/codex/east_wa_brick_storefront_2.webp' },
    { key: 'codex_east_wa_doublewide_tan',      path: 'assets/buildings/codex/east_wa_doublewide_tan.webp' },
    { key: 'codex_east_wa_doublewide_white',    path: 'assets/buildings/codex/east_wa_doublewide_white.webp' },
    { key: 'codex_east_wa_fenced_house_tan',    path: 'assets/buildings/codex/east_wa_fenced_house_tan.webp' },
    { key: 'codex_east_wa_fenced_house_white',  path: 'assets/buildings/codex/east_wa_fenced_house_white.webp' },
    { key: 'codex_east_wa_two_story_brick_shop', path: 'assets/buildings/codex/east_wa_two_story_brick_shop.webp' },
    { key: 'codex_east_wa_block_repair_shop',   path: 'assets/buildings/codex/east_wa_block_repair_shop.webp' },
    { key: 'codex_east_wa_main_street_storefront', path: 'assets/buildings/codex/east_wa_main_street_storefront.webp' },
    { key: 'codex_east_wa_cafe_storefront',      path: 'assets/buildings/codex/east_wa_cafe_storefront.webp' },
    { key: 'codex_east_wa_auto_parts_store',     path: 'assets/buildings/codex/east_wa_auto_parts_store.webp' },
    { key: 'codex_east_wa_market_storefront',    path: 'assets/buildings/codex/east_wa_market_storefront.webp' },
    { key: 'codex_east_wa_vantage_truck_stop',  path: 'assets/buildings/codex/east_wa_vantage_truck_stop.webp' },
    { key: 'codex_east_wa_ritzville_diner_motel', path: 'assets/buildings/codex/east_wa_ritzville_diner_motel.webp' },
    { key: 'codex_east_wa_palouse_farm_store',  path: 'assets/buildings/codex/east_wa_palouse_farm_store.webp' },
    { key: 'codex_east_wa_pullman_party_house', path: 'assets/buildings/codex/east_wa_pullman_party_house.webp' },
    { key: 'codex_west_seattle_horizon_left',       path: 'assets/buildings/codex/west_seattle_horizon_left.png' },
    { key: 'codex_west_seattle_horizon_right',      path: 'assets/buildings/codex/west_seattle_horizon_right.png' },
    { key: 'codex_west_seattle_lowrise_apartments', path: 'assets/buildings/codex/west_seattle_lowrise_apartments.png' },
    { key: 'codex_west_seattle_junction_shops',     path: 'assets/buildings/codex/west_seattle_junction_shops.png' },
    { key: 'codex_west_seattle_warehouse_row',      path: 'assets/buildings/codex/west_seattle_warehouse_row.png' },
    { key: 'codex_west_seattle_hillside_condos',    path: 'assets/buildings/codex/west_seattle_hillside_condos.png' },
    { key: 'codex_west_seattle_overpass_ramp',      path: 'assets/buildings/codex/west_seattle_overpass_ramp.png' },
    // Container cranes flanking the West Seattle Bridge — strict left/right
    // pairing so each side spawns from its own sub-pool (cranes face the road).
    { key: 'codex_ws_crane_crate_left',         path: 'assets/buildings/codex/west_seattle_container_cranes_crate_left.png' },
    { key: 'codex_ws_crane_white_boxes_left',   path: 'assets/buildings/codex/west_seattle_container_cranes_white_boxes_left.png' },
    { key: 'codex_ws_crane_crate_right',        path: 'assets/buildings/codex/west_seattle_container_cranes_crate_right.png' },
    { key: 'codex_ws_crane_white_boxes_right',  path: 'assets/buildings/codex/west_seattle_container_cranes_white_boxes_right.png' },
    { key: 'codex_west_seattle_container_stack_18', path: 'assets/buildings/codex/west_seattle_container_stack_18.png' },
    // West Seattle homes — same Codex building asset folder as Seattle,
    // Bellevue, and Issaquah regional scenery.
    { key: 'west_seattle_1', path: 'assets/buildings/codex/west_seattle_1.png' },
    { key: 'west_seattle_2', path: 'assets/buildings/codex/west_seattle_2.png' },
    { key: 'west_seattle_3', path: 'assets/buildings/codex/west_seattle_3.png' },
    { key: 'west_seattle_4', path: 'assets/buildings/codex/west_seattle_4.png' },
    { key: 'west_seattle_5', path: 'assets/buildings/codex/west_seattle_5.png' },
    { key: 'west_seattle_6', path: 'assets/buildings/codex/west_seattle_6.png' },
  ],
  rural: [
    // One texture instance represents several distant pasture cows. These
    // can be mirrored and staggered in the route for herd variety.
    { key: 'east_wa_herd_3_cows', path: 'assets/rural/eastern_washington/east_wa_herd_3_cows.webp' },
    { key: 'east_wa_herd_5_cows', path: 'assets/rural/eastern_washington/east_wa_herd_5_cows.webp' },
    { key: 'east_wa_herd_6_cows', path: 'assets/rural/eastern_washington/east_wa_herd_6_cows.webp' },
    // Roadside wildlife (owner 2026-08-16) — elk on the Snoqualmie stretch,
    // deer through Cle Elum → Ellensburg.  Spawned via WILDLIFE_BANDS in
    // RouteData as 'livestock' scenery.  The deer_crossing /
    // elk_herd_crossing action plates are deliberately NOT loaded — animals
    // on the pavement are a future hazard feature, not scenery.
    { key: 'elk_bull_roadside',     path: 'assets/wildlife/elk_bull_roadside.png' },
    { key: 'elk_cow_static_facing', path: 'assets/wildlife/elk_cow_static_facing.png' },
    { key: 'deer_roadside',         path: 'assets/wildlife/deer_roadside.png' },
    { key: 'deer_static_facing',    path: 'assets/wildlife/deer_static_facing.png' },
    // Tumbleweeds — roll across the road through the Vantage crosswind zone.
    { key: 'tumbleweed_1', path: 'assets/rural/eastern_washington/tumbleweed_1.png' },
    { key: 'tumbleweed_2', path: 'assets/rural/eastern_washington/tumbleweed_2.png' },
    { key: 'tumbleweed_3', path: 'assets/rural/eastern_washington/tumbleweed_3.png' },
    { key: 'east_wa_fence_post',   path: 'assets/rural/eastern_washington/east_wa_fence_post.webp' },
    { key: 'east_wa_utility_pole_plain', path: 'assets/rural/eastern_washington/east_wa_utility_pole_plain.webp' },
    { key: 'east_wa_utility_pole_transformer', path: 'assets/rural/eastern_washington/east_wa_utility_pole_transformer.webp' },
  ],
  businesses: [
    // Brand-logo placards used by the rest-stop services-sign UI.
    // (biz_cargo / shop_bg_cargo removed 2026-07-29 — CarGo business dropped.)
    { key: 'biz_huffs',      path: 'assets/businesses/huffs.png' },        // Gas
    { key: 'biz_cowbellas',  path: 'assets/businesses/cowbellas.png' },    // Hunting
    { key: 'biz_aok',        path: 'assets/businesses/aok.png' },          // Camp
    { key: 'biz_lord',       path: 'assets/businesses/lord.png' },         // Dealer — Lord Motors (EV)
    { key: 'biz_suck',       path: 'assets/businesses/suck.png' },         // Dealer — Sam's Used Car Kingdom (gas)
    { key: 'biz_gasnsip',    path: 'assets/businesses/gasnsip.png' },      // Vices — Gas-N-Sip (trash gas station)
    { key: 'biz_am_bm',      path: 'assets/businesses/am_bm.png' },        // AM/BM — trash gas station (toilet demolition)
    { key: 'biz_parkride',   path: 'assets/businesses/park-and-ride.png' }, // Park & Ride — Metro Park & Ride
    // The two garages (owner art 2026-07-28).  Both were delivered opaque on a
    // near-white sweep; scripts/keyLogoBackground.js flood-fills the backdrop to
    // alpha so they composite over a storefront instead of showing as a white
    // rectangle.  Originals kept in assets/businesses/raw/.
    { key: 'biz_les_schwasted', path: 'assets/businesses/les_schwasted.png' }, // Tyres / brakes / suspension
    { key: 'biz_fap',           path: 'assets/businesses/fap.png' },           // Finesse Autobody & Performance

    // ── Storefront backdrops ─────────────────────────────────────────────
    // 1672x941 (exactly 16:9, so they map to the 800x450 viewport with no
    // distortion).  These sat unused in the folder until now — nothing loaded
    // or drew them.  The shop screen composites its brand's storefront
    // full-bleed with the menu column over the left third.
    { key: 'shop_bg_huffs',         path: 'assets/businesses/storefront_huffs.png' },
    { key: 'shop_bg_cowbellas',     path: 'assets/businesses/storefront_cowbellas.png' },
    { key: 'shop_bg_aok',           path: 'assets/businesses/storefront_aok.png' },
    { key: 'shop_bg_lord',          path: 'assets/businesses/storefront_lord.png' },
    { key: 'shop_bg_suck',          path: 'assets/businesses/storefront_suck.png' },
    { key: 'shop_bg_gasnsip',       path: 'assets/businesses/storefront_gasnsip.png' },
    { key: 'shop_bg_am_bm',         path: 'assets/businesses/storefront_am_bm.png' },
    { key: 'shop_bg_parkride',      path: 'assets/businesses/storefront_park-and-ride.png' },
    // v2 art (owner-supplied, was sitting unwired in businesses/raw/).
    // Was pointed at raw/les_schwasted_v2.png — which is the LOGO BADGE
    // (1918x820), not a storefront, so the shop screen stretched a floating
    // sign across the whole frame (owner 2026-07-31: "wrong storefront art").
    // The real 1672x941 building shot had been moved to Archive/; restored.
    { key: 'shop_bg_les_schwasted', path: 'assets/businesses/storefront_les_schwasted.png' },
    { key: 'shop_bg_fap',           path: 'assets/businesses/storefront_fap.png' },
    // Highway shield badges — composited onto green exit signs.
    { key: 'hwy_i90',   path: 'assets/businesses/hwy_i90.svg' },
    { key: 'hwy_us195', path: 'assets/businesses/hwy_us195.png' },
    { key: 'hwy_wa26',  path: 'assets/businesses/hwy_wa26.png' },
    { key: 'hwy_wa270', path: 'assets/businesses/hwy_wa270.svg' },
    // Wind warning sign — cantilever overhead.  Sign face hangs over the
    // right travel lane; only the pole base on the shoulder is collidable.
    // Placed once near Vantage (mile ~137).
    { key: 'freeway_sign_wind', path: 'assets/businesses/freeway_sign_wind.png' },
    // The per-stop "SHOPPING - NEXT RIGHT" placards are composed in-engine from
    // these two pieces (src/data/shoppingSign.js) rather than shipped as 19 baked
    // PNGs -- baked signs had no way to know a stop's shops had changed, and spent
    // a while advertising businesses that weren't there.
    { key: 'sign_blank',  path: 'assets/businesses/sign_blank.png'  },
    { key: 'sign_plaque', path: 'assets/businesses/sign_plaque.png' },
  ],
  trees: [
    // Urban broadleaves — Seattle / Mercer Island / Bellevue street &
    // yard trees.  Bigleaf Maple (Acer macrophyllum) is the iconic PNW
    // city tree; vine maple is the understory infill.
    { key: 'tree_bigleaf_maple_1', path: 'assets/trees/bigleaf_maple_1.png' },
    { key: 'tree_bigleaf_maple_2', path: 'assets/trees/bigleaf_maple_2.png' },
    { key: 'tree_vine_maple_1',    path: 'assets/trees/vine_maple_1.png' },
    // Western WA conifers — Bellevue → Issaquah → Snoqualmie Pass.
    // hemlock1/2 + cedar1/2 already on disk; the other species ship as
    // soon as Codex drops the PNGs (paths are pre-registered so the
    // scenery wiring doesn't need a second editing pass).
    { key: 'tree_hemlock1',       path: 'assets/trees/hemlock1.png' },
    { key: 'tree_hemlock2',       path: 'assets/trees/hemlock2.png' },
    { key: 'tree_hemlock3',       path: 'assets/trees/hemlock3.png' },
    { key: 'tree_red_cedar_1',    path: 'assets/trees/red_cedar_1.png' },
    { key: 'tree_red_cedar_2',    path: 'assets/trees/red_cedar_2.png' },
    { key: 'tree_cedar1',         path: 'assets/trees/cedar1.avif' },
    { key: 'tree_cedar2',         path: 'assets/trees/cedar2.png' },
    { key: 'tree_douglas_fir_1',  path: 'assets/trees/douglas_fir_1.png' },
    { key: 'tree_douglas_fir_2',  path: 'assets/trees/douglas_fir_2.png' },
    // Eastern WA — Cle Elum → Ellensburg → Columbia Basin.
    { key: 'tree_ponderosa_1',    path: 'assets/trees/ponderosa_1.png' },
    { key: 'tree_ponderosa_2',    path: 'assets/trees/ponderosa_2.png' },
    { key: 'tree_white_pine_1',   path: 'assets/trees/white_pine_1.png' },
    { key: 'tree_white_pine_2',   path: 'assets/trees/white_pine_2.png' },
    // Columbia Basin shrub-steppe.
    { key: 'shrub_sage_1',        path: 'assets/trees/sage_1.png' },
    { key: 'shrub_sage_2',        path: 'assets/trees/sage_2.png' },
    { key: 'shrub_rabbitbrush_1', path: 'assets/trees/rabbitbrush_1.png' },
    // Legacy placeholder — kept as final fallback.
    { key: 'tree_generic',        path: 'assets/trees/tree1.png' },
  ],
  weapons: [
    // Circular medallions shared by road pickups, shops and F12 HUD cells.
    { key: 'weapon_coal',        path: 'assets/weapons/rolling_coal.png' },
    { key: 'weapon_fireworks',   path: 'assets/weapons/fireworks.png' },
    { key: 'weapon_paint_bomb',  path: 'assets/weapons/paint_bomb.png' },
    { key: 'weapon_disguise',    path: 'assets/weapons/disguise.png' },
  ],
  cops: [
    // Police cop sprites are sourced from the car_back_police /
    // car_front_police pair in `cars` above.  The single cop_police
    // texture is kept as a legacy fallback only.
    { key: 'cop_police',  path: 'assets/cops/police.png' },
    // 5★ chase helicopter — two rotor frames per facing direction.
    // The renderer alternates 1 ↔ 2 at ~10 Hz for the rotor-spin
    // illusion and uses the _flip variants when the chopper is shown
    // banking the opposite way.
    { key: 'cop_heli_1',      path: 'assets/cops/heli_1.png' },
    { key: 'cop_heli_2',      path: 'assets/cops/heli_2.png' },
    { key: 'cop_heli_1_flip', path: 'assets/cops/heli_1_flip.png' },
    { key: 'cop_heli_2_flip', path: 'assets/cops/heli_2_flip.png' },
  ],
  // (props removed — prop_marker + prop_blood were vestigial manifest
  //  entries with no gameplay code referencing them.)
  ui: [
    // Loaded first by BootScene so the remaining asset fetches have a
    // title-quality neon splash behind the live progress bar.
    { key: 'ui_loading_screen',   path: 'assets/ui/loading_screen.png?v=rtr-1' },
    { key: 'ui_end_crashed_neon', path: 'assets/ui/end_crashed_neon.webp' },
    { key: 'ui_end_passed_out_neon', path: 'assets/ui/end_passed_out_neon.webp' },
    { key: 'ui_end_busted_screen', path: 'assets/ui/end_busted_screen.webp' },
    // License-plate art — one US state plate per save slot (slot 0/1/2 →
    // WA/OR/ID).  Used on the title-screen "WHO'S DRIVING?" slots AND on the
    // active player's car rear bumper.  827×374 source, shipped at 480×218.
    { key: 'plate_wa',           path: 'assets/ui/plates/plate_wa.png' },
    { key: 'plate_or',           path: 'assets/ui/plates/plate_or.png' },
    { key: 'plate_id',           path: 'assets/ui/plates/plate_id.png' },
    // Gas-gauge HUD swap.  Full pump shows above 30 mi remaining,
    // empty pump shows once the tank is at 30 mi or less.
    { key: 'ui_gas_full',        path: 'assets/ui/gas_full.png' },
    { key: 'ui_gas_empty',       path: 'assets/ui/gas_empty.png' },
    { key: 'ui_top_btn_genre',   path: 'assets/ui/top_btn_genre.png' },
    { key: 'ui_top_btn_mute',    path: 'assets/ui/top_btn_mute.png' },
    { key: 'ui_top_btn_unmute',  path: 'assets/ui/top_btn_unmute.png' },
    { key: 'ui_top_btn_map',     path: 'assets/ui/top_btn_map.png' },
    // Tutorial "?" — HUD tile pair (replaces the in-game Garage shortcut,
    // owner 2026-09-03) + standalone caution-sign pair for the title screen.
    { key: 'ui_top_btn_tutorial',         path: 'assets/ui/top_btn_tutorial.png' },
    { key: 'ui_top_btn_tutorial_active',  path: 'assets/ui/top_btn_tutorial_active.png' },
    { key: 'ui_menu_btn_tutorial',        path: 'assets/ui/menu_btn_tutorial.png' },
    { key: 'ui_menu_btn_tutorial_active', path: 'assets/ui/menu_btn_tutorial_active.png' },
    // ── Garage upgrade UI (owner art, 2026-07-28) ────────────────────
    // Toolbar is a 1672x220 strip of SEVEN category tabs with the labels
    // already baked into the art (TIRES / BRAKES / SUSPENSION / ENGINE /
    // FUEL / COOLANT / WIPERS-HEADLIGHTS), first tab drawn in a magenta
    // selected state.  The renderer slices it into 7 equal columns and
    // re-tints for selection rather than needing per-tab files.
    { key: 'ui_garage_toolbar',  path: 'assets/ui/garage_upgrade_toolbar.png' },
    // 1254x1254 hero product shots, one per toolbar category — used as the
    // row thumbnail beside each upgrade in that category.
    { key: 'garage_ico_tires',      path: 'assets/ui/garage_buttons/tires.png' },
    { key: 'garage_ico_brakes',     path: 'assets/ui/garage_buttons/brakes.png' },
    { key: 'garage_ico_suspension', path: 'assets/ui/garage_buttons/suspension.png' },
    { key: 'garage_ico_engine',     path: 'assets/ui/garage_buttons/engine.png' },
    { key: 'garage_ico_fuel',       path: 'assets/ui/garage_buttons/fuel.png' },
    { key: 'garage_ico_coolant',    path: 'assets/ui/garage_buttons/coolant.png' },
    { key: 'garage_ico_wipers',     path: 'assets/ui/garage_buttons/wipers_headlights.png' },
    { key: 'ui_top_btn_ff',      path: 'assets/ui/top_btn_ff.png' },
    { key: 'ui_top_btn_ff_active', path: 'assets/ui/top_btn_ff_active.png' },
    { key: 'ui_top_btn_pause',   path: 'assets/ui/top_btn_pause.png' },
    { key: 'ui_top_btn_pause_active', path: 'assets/ui/top_btn_pause_active.png' },
    // Tactile driving-control faces. Runtime keeps the existing hit areas,
    // labels, toggle feedback, and controls-editor sizing around this art.
    { key: 'ui_control_wiper',   path: 'assets/ui/control_wiper.png?v=automotive-1' },
    { key: 'ui_control_accel',   path: 'assets/ui/control_accel.png?v=automotive-1' },
    { key: 'ui_control_brake',   path: 'assets/ui/control_brake.png?v=automotive-1' },
    // Gas-gauge warning icon (from DUI) — full/empty swap on the analog gauge.
    { key: 'ui_gas_full',        path: 'assets/ui/gas_full.png' },
    { key: 'ui_gas_empty',       path: 'assets/ui/gas_empty.png' },
    // Portrait phone-as-menu background.  Rotating the device to
    // portrait (or pressing M on desktop) launches PhoneMenuScene with
    // this PNG as the full-screen letterboxed background.
    { key: 'ui_phone_menu_bg',   path: 'assets/ui/iphone_menu_bg.png' },
    // Full-frame neon/rain title treatment. Runtime copy is sized to the
    // 800x450 game viewport; the authored full-size PNG stays in Images/.
    { key: 'ui_title_screen',     path: 'assets/ui/title_screen.png?v=rtr-1' },
    // (Removed ui_title_d / ui_title_u / ui_title_i — the old per-letter intro
    //  art was deleted in the title overhaul; the manifest entries pointed at
    //  missing files and threw "Failed to process file" + a WebGL texImage2D
    //  out-of-range error every load.  The title now uses ui_title_screen.)
  ],
};

export function flattenManifest() {
  return Object.values(ASSET_MANIFEST).flat();
}

// ── Genre / Culture art (owner 2026-07-17) ───────────────────────────────
// When a genre is selected (a music station = a genre), these texture keys load
// from public/assets/culture/<genre>/ instead of the defaults — reskinning the
// vice sprites + the starting vehicle to match the chosen culture. Applied at
// boot (BootScene) and live on selection (GameScene._applyGenreArt).
export const GENRE_ART = {
  vice_sushi:        'vices/sushi.png',
  vice_burrito:      'vices/burrito.png',
  vice_energy:       'vices/energy_shot.png',
  vice_gummies:      'vices/gummies.png',
  vice_hotdog:       'vices/hotdog.png',
  vice_combo:        'vices/combo_meal.png',
  vice_coldbrew:     'vices/cold_brew.png',
  vice_coma:         'vices/food_coma.png',
  vice_slushie:      'vices/slushie.png',
  vice_caffeine:     'vices/caffeine_pills.png',
  vice_water:        'vices/water.png',
  vice_dramamine:    'vices/dramamine.png',
  powerup_rage:      'vices/redneck_rage.png',
  powerup_espresso:  'vices/emergency_espresso.png',
  // Starting vehicle (the beater) front/back → the genre's starter art.
  codex_beater_front: 'vehicles/starter_front.png',
  codex_beater_back:  'vehicles/starter_back.png',
  codex_beater_back_turn: 'vehicles/starter_back_turn.png',
  codex_beater_back_turn_007: 'vehicles/starter_back_turn_007.png',
  codex_beater_back_turn_012: 'vehicles/starter_back_turn_012.png',
  codex_beater_spin_030: 'vehicles/starter_spin_030.png',
  codex_beater_spin_060: 'vehicles/starter_spin_060.png',
  codex_beater_spin_090: 'vehicles/starter_spin_090.png',
  codex_beater_spin_120: 'vehicles/starter_spin_120.png',
  codex_beater_spin_150: 'vehicles/starter_spin_150.png',
};

/** Culture-art path for a manifest key under the given genre, or null if this
 *  key has no genre override (falls back to the default manifest path). */
export function genreArtPath(key, genre) {
  if (!genre || !GENRE_ART[key]) return null;
  // Vehicle art gets its own revision so an installed/PWA build cannot keep
  // stale versions after refresh.  angleset-1 = the 2026-08-27 full angle-set
  // re-export (back/turn/front/spins all replaced in place).
  const vehicleRev = key.startsWith('codex_beater') ? '&v=angleset-1' : '';
  return `assets/culture/${genre}/${GENRE_ART[key]}?g=${genre}${vehicleRev}`;
}

// Default (non-culture) manifest path for each GENRE_ART key — used to REVERT
// the reskin to base art when a plate has no genre selected (owner 2026-07-17).
const _MANIFEST_BY_KEY = Object.fromEntries(flattenManifest().map(e => [e.key, e.path]));
/** Base manifest path for a GENRE_ART key, or null if unknown. */
export function genreDefaultPath(key) {
  return GENRE_ART[key] ? (_MANIFEST_BY_KEY[key] ?? null) : null;
}
